### ISSUE TITLE
Biografia Alfredo

### ISSUE THREAD

**Issue by jorgearamos9** [redglobalmxraleigh/redglobalmxraleighSite#5]
- [x] Falta foto de Alfredo
- [ ] Biografia 
[Red Global MX - Alfredo's Bio.docx](https://github.com/redglobalmxraleigh/redglobalmxraleighSite/files/1798865/Red.Global.MX.-.Alfredo.s.Bio.docx)

**Comment by jorgearamos9** [comment]
![img_7456](https://user-images.githubusercontent.com/20178097/37243975-35d4022c-2450-11e8-8ba0-5a2f1742bfee.JPG)
![img_7453](https://user-images.githubusercontent.com/20178097/37243976-35df4fb0-2450-11e8-9c8f-04093c12e179.JPG)

**Comment by enriquemnz** [comment]
Done, listo para el server de prueba!
