### ISSUE TITLE
Biografia Elsa

### ISSUE THREAD

**Issue by jorgearamos9** [redglobalmxraleigh/redglobalmxraleighSite#7]
- [X] Bio attached 
[Bio-Elsa Jimenez 2017.docx](https://github.com/redglobalmxraleigh/redglobalmxraleighSite/files/1799085/Bio-Elsa.Jimenez.2017.docx)

- [x] Fotos attached
[FotosElsa.zip](https://github.com/redglobalmxraleigh/redglobalmxraleighSite/files/1799087/FotosElsa.zip)

**Comment by jorgearamos9** [comment]
Elsa, que foto es la que te gusta mas ?

**Comment by elsamaria** [comment]
La 4837 Jorge, creo que es la segunda. Muchas Gracias!

**Comment by enriquemnz** [comment]
Done, listo para el server de prueba!

**Comment by elsamaria** [comment]
Necesitan que yo haga algo de mi parte? o lo mío ya quedo?

**Comment by redglobalmxraleigh** [comment]
Hola @elsamaria, solo falta que veas a ver como quedo en el site de pruebas a ver si no tienes comentarios. Este es: http://redglobalmxraleigh.com/test/#/conocenos/
