### ISSUE TITLE
Biografia Luisa

### ISSUE THREAD

**Issue by jorgearamos9** [redglobalmxraleigh/redglobalmxraleighSite#8]
- [ ] Falta Bio attached 

- [X] Fotos attached
[FotosLuisa.zip](https://github.com/redglobalmxraleigh/redglobalmxraleighSite/files/1799089/FotosLuisa.zip)

**Comment by redglobalmxraleigh** [comment]
Hola Enrique, aqui esta la Bio y la foto que Luisa selecciono, puedes hacer el cambio para ponerlo en pruebas y que lo revise Luisa pls ?
[Bio - Luisa Scott.docx](https://github.com/redglobalmxraleigh/redglobalmxraleighSite/files/1808042/Bio.-.Luisa.Scott.docx)
![img_6287](https://user-images.githubusercontent.com/20178119/37359760-d0877116-26c4-11e8-8964-73ded1bf8a92.JPG)

**Comment by enriquemnz** [comment]
Done, listo para el server de prueba!
